export const photos = [
    {
        "src":"/pataint1.jpg",
        "width":800,
        "height":600
    },
    {
        "src":"/minroscope.jpg",
        "width":800,
        "height":600
    },
    {
        "src":"/pataint.jpg",
        "width":800,
        "height":600
    },
    {
        "src":"/doctor1.jpg",
        "width":800,
        "height":600
    },
    {
        "src":"/d.jpg",
        "width":800,
        "height":600
    },
    {
        "src":"/pataint1.jpg",
        "width":800,
        "height":600
    },
    {
        "src":"/pataint1.jpg",
        "width":800,
        "height":600
    },
    {
        "src":"/pataint1.jpg",
        "width":800,
        "height":600
    },
    {
        "src":"/pataint1.jpg",
        "width":800,
        "height":600
    },
    {
        "src":"/pataint1.jpg",
        "width":800,
        "height":600
    },
    {
        "src":"/pataint1.jpg",
        "width":800,
        "height":600
    },
    {
        "src":"/pataint1.jpg",
        "width":800,
        "height":600
    }
]